import MainLayout from "components/homepage/MainLayout";
import SortBar from "components/sellingpage/SortBar";
import Head from "next/head";
import React from "react";

const SellingPage = () => {
  return (
    <>
      <Head>
        <title>Cần bán nhà đất | Nhà phố VN</title>
        <meta name="description" content="Generated by create home page" />
      </Head>
      <MainLayout>
        <SortBar />
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
        <h1>hello</h1>
      </MainLayout>
    </>
  );
};

export default SellingPage;
