import HeroSection from "components/homepage/HeroSection";
import HomeCollection from "components/homepage/HomeCollection";
import HomeCompanyProject from "components/homepage/HomeCompanyProject";
import HomeMillions from "components/homepage/HomeMillions";
import HomeProperty from "components/homepage/HomeProperty";
import HomeRent from "components/homepage/HomeRent";
import MainLayout from "components/homepage/MainLayout";
import Head from "next/head";
import * as React from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Nhà phố sài gòn</title>
        <meta name="description" content="Generated by create home page" />
      </Head>
      <HeroSection />
      <MainLayout>
        <HomeMillions />
        <HomeProperty />
        <HomeCompanyProject />
        <HomeRent />
        <HomeCollection />
      </MainLayout>
    </>
  );
}
